version: "3"

services:
  app:
    build:
      context: ./
      dockerfile: docker/python/Dockerfile
    container_name: 'flask-application'
    volumes:
      - .:/application
    ports:
      - "5050:5050"
    networks:
      - app

networks:
  app:
    driver: bridge
